import crypto from 'node:crypto';

const SESSION_TTL_MS = Number(process.env.SESSION_TTL_MS || 8 * 60 * 60 * 1000);
const LOGIN_MAX_ATTEMPTS = Number(process.env.LOGIN_MAX_ATTEMPTS || 5);
const LOGIN_LOCK_BASE_MS = Number(process.env.LOGIN_LOCK_BASE_MS || 30_000);
const LOGIN_LOCK_MAX_MS = Number(process.env.LOGIN_LOCK_MAX_MS || 15 * 60 * 1000);
/** How long an idle attempt counter is kept before being forgotten. */
const LOGIN_ATTEMPT_TTL_MS = Number(process.env.LOGIN_ATTEMPT_TTL_MS || 60 * 60 * 1000);

const SCRYPT_KEYLEN = 64;

/**
 * Sessions live in memory only. A backend restart invalidates every session,
 * which is the safe default for an operations console.
 */
const sessions = new Map();
const loginAttempts = new Map();

function scryptHash(password, salt) {
  return new Promise((resolve, reject) => {
    crypto.scrypt(password, salt, SCRYPT_KEYLEN, (error, derivedKey) => {
      if (error) {
        reject(error);
        return;
      }
      resolve(derivedKey);
    });
  });
}

/**
 * Stored format: scrypt$<saltHex>$<hashHex>. Generated by `npm run hash-password`.
 */
export function parsePasswordHash(stored) {
  const parts = String(stored || '').split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') {
    return undefined;
  }

  const salt = Buffer.from(parts[1], 'hex');
  const hash = Buffer.from(parts[2], 'hex');
  if (salt.length === 0 || hash.length !== SCRYPT_KEYLEN) {
    return undefined;
  }

  return { salt, hash };
}

export async function createPasswordHash(password) {
  const salt = crypto.randomBytes(16);
  const hash = await scryptHash(password, salt);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

function timingSafeEqualString(a, b) {
  const bufferA = Buffer.from(String(a));
  const bufferB = Buffer.from(String(b));

  // timingSafeEqual throws on length mismatch, so compare digests instead.
  const digestA = crypto.createHash('sha256').update(bufferA).digest();
  const digestB = crypto.createHash('sha256').update(bufferB).digest();

  return crypto.timingSafeEqual(digestA, digestB);
}

function getAttemptState(key) {
  const state = loginAttempts.get(key);
  if (!state) {
    return { count: 0, lockedUntil: 0 };
  }
  return state;
}

export function getLoginLockRemainingMs(key) {
  const { lockedUntil } = getAttemptState(key);
  const remaining = lockedUntil - Date.now();
  return remaining > 0 ? remaining : 0;
}

/**
 * Drops attempt counters that are no longer blocking.
 *
 * Without this the map grows one entry per distinct source IP forever, which a
 * distributed login flood turns into unbounded memory use.
 */
function pruneLoginAttempts() {
  const now = Date.now();
  for (const [key, state] of loginAttempts.entries()) {
    const expired =
      state.lockedUntil > 0
        ? state.lockedUntil <= now
        : now - (state.lastAttemptAt || 0) > LOGIN_ATTEMPT_TTL_MS;

    if (expired) {
      loginAttempts.delete(key);
    }
  }
}

function registerFailedAttempt(key) {
  pruneLoginAttempts();

  const state = getAttemptState(key);
  const count = state.count + 1;

  let lockedUntil = 0;
  if (count >= LOGIN_MAX_ATTEMPTS) {
    const overflow = count - LOGIN_MAX_ATTEMPTS;
    const lockMs = Math.min(
      LOGIN_LOCK_BASE_MS * Math.pow(2, overflow),
      LOGIN_LOCK_MAX_MS
    );
    lockedUntil = Date.now() + lockMs;
  }

  loginAttempts.set(key, { count, lockedUntil, lastAttemptAt: Date.now() });
}

function clearAttempts(key) {
  loginAttempts.delete(key);
}

function pruneSessions() {
  const now = Date.now();
  for (const [token, session] of sessions.entries()) {
    if (session.expiresAt <= now) {
      sessions.delete(token);
    }
  }
}

export function createSession(user) {
  pruneSessions();
  const token = crypto.randomBytes(32).toString('base64url');
  sessions.set(token, {
    user,
    expiresAt: Date.now() + SESSION_TTL_MS,
  });
  return token;
}

export function resolveSession(token) {
  if (!token) {
    return undefined;
  }

  const session = sessions.get(token);
  if (!session) {
    return undefined;
  }

  if (session.expiresAt <= Date.now()) {
    sessions.delete(token);
    return undefined;
  }

  // Sliding expiration: an operator working continuously is not logged out.
  session.expiresAt = Date.now() + SESSION_TTL_MS;
  return session;
}

export function destroySession(token) {
  if (token) {
    sessions.delete(token);
  }
}

/**
 * Reads the auth configuration and fails loudly when it is incomplete.
 * The console proxies full Coolify admin power, so running it without
 * credentials is never an acceptable fallback.
 */
export function loadAuthConfig(env = process.env) {
  const user = String(env.WEB_AUTH_USER || '').trim();
  const passwordHash = String(env.WEB_AUTH_PASSWORD_HASH || '').trim();
  const plainPassword = String(env.WEB_AUTH_PASSWORD || '').trim();
  const serviceToken = String(env.WEB_ACCESS_TOKEN || '').trim();

  const errors = [];

  if (!user) {
    errors.push('WEB_AUTH_USER is required.');
  }

  let parsedHash;
  if (passwordHash) {
    parsedHash = parsePasswordHash(passwordHash);
    if (!parsedHash) {
      errors.push(
        'WEB_AUTH_PASSWORD_HASH is malformed. Expected "scrypt$<saltHex>$<hashHex>" from `npm run hash-password`.'
      );
    }
  } else if (!plainPassword) {
    errors.push(
      'WEB_AUTH_PASSWORD_HASH is required (generate it with `npm run hash-password`).'
    );
  }

  if (serviceToken && serviceToken.length < 32) {
    errors.push('WEB_ACCESS_TOKEN must have at least 32 characters.');
  }

  return {
    user,
    parsedHash,
    plainPassword: parsedHash ? '' : plainPassword,
    serviceToken,
    errors,
  };
}

export async function verifyCredentials(authConfig, username, password) {
  if (!username || !password) {
    return false;
  }

  if (!timingSafeEqualString(username, authConfig.user)) {
    return false;
  }

  if (authConfig.parsedHash) {
    const candidate = await scryptHash(password, authConfig.parsedHash.salt);
    return crypto.timingSafeEqual(candidate, authConfig.parsedHash.hash);
  }

  return timingSafeEqualString(password, authConfig.plainPassword);
}

export function getBearerToken(req) {
  const auth = req.headers.authorization || '';
  if (!auth.toLowerCase().startsWith('bearer ')) {
    return '';
  }
  return auth.slice(7).trim();
}

/**
 * Express middleware. Accepts either a login session or the fixed service
 * token used by automations. The actor is always derived here, never from a
 * client-supplied header, so the audit trail cannot be forged.
 */
export function createAuthMiddleware(authConfig) {
  return function requireWebAuth(req, res, next) {
    const token = getBearerToken(req);

    if (!token) {
      res.status(401).json({ message: 'Nao autenticado.' });
      return;
    }

    if (authConfig.serviceToken && timingSafeEqualString(token, authConfig.serviceToken)) {
      req.actor = 'service-token';
      next();
      return;
    }

    const session = resolveSession(token);
    if (!session) {
      res.status(401).json({ message: 'Sessao invalida ou expirada.' });
      return;
    }

    req.actor = session.user;
    req.sessionToken = token;
    next();
  };
}

export function registerLoginFailure(key) {
  registerFailedAttempt(key);
}

export function registerLoginSuccess(key) {
  clearAttempts(key);
}

export const authInternals = {
  sessions,
  loginAttempts,
  SESSION_TTL_MS,
  LOGIN_MAX_ATTEMPTS,
};
